using System.Text;

namespace Persistence.Migration.Builders;

internal static class BeginEndBuilder
{
    #region BuildBegin

    public static void BuildBegin(
        string artifactFolder,
        string artifactPrefix,
        string schema,
        string tableName)
    {
        ValidateArguments(
            artifactFolder,
            artifactPrefix,
            schema,
            tableName);

        string packagePath =
            BuildPackagePath(
                artifactFolder,
                schema,
                tableName);

        Directory.CreateDirectory(packagePath);

        string filePath =
            Path.Combine(
                packagePath,
                $"BEGIN_{schema}.{artifactPrefix}_{tableName}.sql");

        string sql =
            BuildBeginScript(
                artifactPrefix,
                schema,
                tableName);

        WriteFile(
            filePath,
            sql);
    }

    #endregion

    #region BuildEnd
    public static void BuildEnd(
        string artifactFolder,
        string artifactPrefix,
        string schema,
        string tableName)
    {
        ValidateArguments(
            artifactFolder,
            artifactPrefix,
            schema,
            tableName);

        string packagePath =
            BuildPackagePath(
                artifactFolder,
                schema,
                tableName);

        Directory.CreateDirectory(packagePath);

        string filePath =
            Path.Combine(
                packagePath,
                $"END_{schema}.{artifactPrefix}_{tableName}.sql");

        string sql =
            BuildEndScript(
                artifactPrefix,
                schema,
                tableName);

        WriteFile(
            filePath,
            sql);
    }
    #endregion

    #region BuildBeginScript

    private static string BuildBeginScript(
        string artifactPrefix,
        string schema,
        string tableName)
    {
        Boolean isIntegration = false;
        if (artifactPrefix == "INT")
        {
            isIntegration = true;
        }

        int deleteBatchSize =
            artifactPrefix.Equals(
                "WF",
                StringComparison.OrdinalIgnoreCase)
                ? 6000
                : 4000;

        if (isIntegration)
        {
            return
$"""
/*
    Package  : {schema}.{tableName}
    GENERATED BY Sistran.MigrationBuilder
    Artifact : BEGIN
*/
                
-- ===========================================================
-- Preparación de la migración
-- Descomente únicamente las instrucciones necesarias.
-- ===========================================================
""";

        }

        return
$"""
/*
    Package  : {schema}.{tableName}
    GENERATED BY Sistran.MigrationBuilder
    Artifact : BEGIN
*/

-- ===========================================================
-- Preparación de la migración
-- Descomente únicamente las instrucciones necesarias.
-- ===========================================================

-- Deshabilitar restricciones
-- ALTER TABLE [{schema}].[{tableName}] NOCHECK CONSTRAINT ALL;

-- Deshabilitar triggers
-- DISABLE TRIGGER ALL ON [{schema}].[{tableName}];

-- Limpiar tabla de destino
SET NOCOUNT ON;
WHILE 1 = 1
BEGIN
    DELETE TOP ({deleteBatchSize})
    FROM [{schema}].[{tableName}];

    IF @@ROWCOUNT = 0
        BREAK;
END;

-- Permitir insertar valores Identity
-- SET IDENTITY_INSERT [{schema}].[{tableName}] ON;
""";
    }

    #endregion

    #region BuildEndScript
    private static string BuildEndScript(
        string artifactPrefix,
        string schema,
        string tableName)
    {
        if (artifactPrefix == "INT")
        {
            return
$"""
/*
    Package  : {schema}.{tableName}
    Artifact : END
*/

-- ===========================================================
-- Finalización de la integración
-- Descomente únicamente las instrucciones necesarias.
-- ===========================================================
""";
        }

        return
$"""
/*
    Package  : {schema}.{tableName}
    Artifact : END
*/

-- ===========================================================
-- Finalización de la migración
-- Descomente únicamente las instrucciones necesarias.
-- ===========================================================

-- Eliminar tabla de trabajo
IF OBJECT_ID(N'[{schema}].[{artifactPrefix}_{tableName}]', N'U') IS NOT NULL
BEGIN
    DROP TABLE [{schema}].[{artifactPrefix}_{tableName}];
END

-- Deshabilitar Identity Insert
-- SET IDENTITY_INSERT [{schema}].[{tableName}] OFF;

-- Habilitar triggers
-- ENABLE TRIGGER ALL ON [{schema}].[{tableName}];

-- Habilitar restricciones
-- ALTER TABLE [{schema}].[{tableName}] WITH CHECK CHECK CONSTRAINT ALL;

-- Actualizar estadísticas
UPDATE STATISTICS [{schema}].[{tableName}];

-- Verificar integridad de la tabla
DBCC CHECKTABLE ('[{schema}].[{tableName}]');
""";
    }
    #endregion

    #region BuildPackagePath

    private static string BuildPackagePath(
        string artifactFolder,
        string schema,
        string tableName)
    {
        return Path.Combine(
            artifactFolder,
            $"{schema}.{tableName}");
    }

    #endregion

    #region ValidateArguments

    private static void ValidateArguments(
        string artifactFolder,
        string artifactPrefix,
        string schema,
        string tableName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(
            artifactFolder);

        ArgumentException.ThrowIfNullOrWhiteSpace(
            artifactPrefix);

        ArgumentException.ThrowIfNullOrWhiteSpace(
            schema);

        ArgumentException.ThrowIfNullOrWhiteSpace(
            tableName);
    }

    #endregion

    #region WriteFile

    private static void WriteFile(
        string filePath,
        string content)
    {
        File.WriteAllText(
            filePath,
            content,
            Encoding.UTF8);
    }

    #endregion
}