using DataToolkit.Library;
using Domain.Enums;
using Persistence.Migration.Helpers;

namespace Persistence.Migration.Builders;

internal static class DdlBuilder
{
    #region BuildCreateTable
    public static string BuildCreateTable(
        TableMetadata? sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        string artifactPrefix = MigrationWarningExtensions.GetArtifactPrefix(artifactType);
        bool isIntegration = artifactType == ArtifactType.Integration;

        List<string> columns = [];

        //Adicionar columna ExecutionId
        if (isIntegration)
        {
            columns.Add(BuildExecutionId());
        }
            
        //Concatenar columnas
        for (int i = 0; i < targetTable.Columns.Count; i++)
        {
            ColumnMetadata targetColumn = targetTable.Columns[i];

            ColumnMetadata? sourceColumn =
                sourceTable?.Columns.FirstOrDefault(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            bool appendComma =
                isIntegration ||
                i < targetTable.Columns.Count - 1;

            columns.Add(
                BuildColumn(
                    sourceColumn,
                    targetColumn,
                    appendComma,
                    artifactType));
        }

        // Crea llave primaria si es integracion
        if (isIntegration)
        {
            columns.Add(
                BuildIntegrationPrimaryKey(
                    targetTable));
        }

        string columnScript =
            string.Join(
                Environment.NewLine,
                columns);

        return BuildCreateTableScript(
            artifactPrefix,
            targetTable.Schema,
            targetTable.Name,
            columnScript);
    }
    #endregion

    #region BuildColumn
    public static string BuildColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn,
        bool appendComma,
        ArtifactType artifactType)
    {
        string warning =
            Common.BuildWarning(
                sourceColumn,
                targetColumn);

        string comma =
            appendComma ? "," : string.Empty;

        bool isIntegration =
            artifactType == ArtifactType.Integration;

        string nullability =
            isIntegration && targetColumn.IsPrimaryKey
                ? "NOT NULL"
                : "NULL";

        return
            $"        [{targetColumn.Name}] {Common.BuildSqlType(targetColumn)} {nullability}{comma}{warning}";
    }
    #endregion

    #region BuildIntegrationPrimaryKey
    private static string BuildIntegrationPrimaryKey(
        TableMetadata targetTable)
    {
        List<string> primaryKeyColumns =
            targetTable.Columns
                .Where(
                    column => column.IsPrimaryKey)
                .Select(
                    column => column.Name)
                .ToList();

        if (primaryKeyColumns.Count == 0)
        {
            throw new InvalidOperationException(
                $"La tabla '{targetTable.Schema}.{targetTable.Name}' " +
                "no tiene llave primaria.");
        }

        string columns =
            string.Join(
                "," + Environment.NewLine,
                primaryKeyColumns.Select(
                    column =>
                        $"        [{column}]"));

        return
    $"""
    CONSTRAINT [PK_INT_{targetTable.Name}]
        PRIMARY KEY NONCLUSTERED
        (
        [ExecutionId],
{columns}
        )
        WITH
        (
            ALLOW_ROW_LOCKS = ON,
            ALLOW_PAGE_LOCKS = ON
        )
""";
    }
    #endregion

    #region BuildCreateTableScript
    private static string BuildCreateTableScript(
        string artifactPrefix,
        string schema,
        string tableName,
        string columnScript)
    {
        return
    $"""
/*
====================================================
TABLE : {artifactPrefix}_{tableName}
GENERATED BY Sistran.MigrationBuilder
- No constraints, No identities, All columns nullable.
====================================================
*/
IF OBJECT_ID('{schema}.{artifactPrefix}_{tableName}') IS NOT NULL
BEGIN
    DROP TABLE [{schema}].[{artifactPrefix}_{tableName}];
END
GO
CREATE TABLE [{schema}].[{artifactPrefix}_{tableName}]
(
{columnScript}
);
GO
""";
    }
    #endregion

    #region BuildExecutionId
    private static string BuildExecutionId()
    {
        return
"        [ExecutionId] CHAR(26) NOT NULL," +
Environment.NewLine +
"        [OperationCD] CHAR(1) NOT NULL,";
    }
    #endregion
}
