using DataToolkit.Library;
using Domain.Enums;
using Persistence.Migration.Helpers;

namespace Persistence.Migration.Builders;

internal static class DdlBuilder
{
    #region BuildCreateTable
    public static string BuildCreateTable(
        TableMetadata? sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        string artifactPrefix =
            artifactType == ArtifactType.WorkFile
                ? "WF"
                : "STG";

        List<string> columns = [];

        for (int i = 0; i < targetTable.Columns.Count; i++)
        {
            ColumnMetadata targetColumn = targetTable.Columns[i];

            ColumnMetadata? sourceColumn =
                sourceTable?.Columns.FirstOrDefault(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            bool appendComma =
                i < targetTable.Columns.Count - 1;

            columns.Add(
                BuildColumn(
                    sourceColumn,
                    targetColumn,
                    appendComma));
        }

        string columnScript =
            string.Join(
                Environment.NewLine,
                columns);

        return
$"""
/*
====================================================
TABLE : {artifactPrefix}_{targetTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
- No constraints, No identities, All columns nullable.
====================================================
*/
IF OBJECT_ID('{targetTable.Schema}.{artifactPrefix}_{targetTable.Name}') IS NOT NULL
BEGIN
    DROP TABLE [{targetTable.Schema}].[{artifactPrefix}_{targetTable.Name}];
END
GO
CREATE TABLE [{targetTable.Schema}].[{artifactPrefix}_{targetTable.Name}]
(
{columnScript}
);
GO
""";
    }
    #endregion

    #region BuildColumn
    public static string BuildColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn,
        bool appendComma)
    {
        string warning =
            Common.BuildWarning(
                sourceColumn,
                targetColumn);

        string comma =
            appendComma ? "," : string.Empty;

        return
            $"        [{targetColumn.Name}] {Common.BuildSqlType(targetColumn)} NULL{comma}{warning}";
    }
    #endregion
}