using DataToolkit.Library;
using Domain.Enums;
using Persistence.Migration.Helpers;

namespace Persistence.Migration.Builders;

internal static class ExtractionBuilder
{
    #region BuildExtractionScript
    public static string BuildExtractionScript(
        TableMetadata sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        return artifactType switch
        {
            ArtifactType.WorkFile => BuildSelect(artifactType, sourceTable, targetTable),
            ArtifactType.Staging => BuildSelect(artifactType, sourceTable, targetTable),
            _ => throw new NotSupportedException()
        };
    }
    #endregion

    #region BuildQueryColumn
    private static string BuildQueryColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn,
        bool appendComma)
    {
        string expression;

        if (sourceColumn is not null)
        {
            expression = $"[{sourceColumn.Name}]";

            if (!string.IsNullOrWhiteSpace(sourceColumn.Collation) &&
                !string.IsNullOrWhiteSpace(targetColumn.Collation) &&
                !sourceColumn.Collation.Equals(
                    targetColumn.Collation,
                    StringComparison.OrdinalIgnoreCase))
            {
                expression += $" COLLATE {targetColumn.Collation}";
            }
        }
        else
        {
            expression = MigrationWarningExtensions.GetDefaultValue(targetColumn);
        }

        string warning =
            Common.BuildWarning(
                sourceColumn,
                targetColumn);

        string comma =
            appendComma ? "," : string.Empty;

        return
            $"    {expression} AS [{targetColumn.Name}]{comma}{warning}";
    }
    #endregion

    #region BuildSelect
    private static string BuildSelect(
        ArtifactType artifactType,
        TableMetadata sourceTable,
        TableMetadata targetTable)
    {
        List<string> selectColumns = [];

        string prefix =
            artifactType == ArtifactType.WorkFile
                ? "WF"
                : "STG";

        for (int i = 0; i < targetTable.Columns.Count; i++)
        {
            ColumnMetadata targetColumn = targetTable.Columns[i];

            ColumnMetadata? sourceColumn =
                sourceTable.Columns.FirstOrDefault(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            bool appendComma =
                i < targetTable.Columns.Count - 1;

            selectColumns.Add(
                BuildQueryColumn(
                    sourceColumn,
                    targetColumn,
                    appendComma));
        }

        string select =
            string.Join(
                Environment.NewLine,
                selectColumns);

        return
$"""
/*
====================================================
TABLE : {prefix}_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
====================================================
*/

SELECT
{select}
FROM [{sourceTable.Schema}].[{sourceTable.Name}];
""";
    }
    #endregion
}