using DataToolkit.Library;

namespace Persistence.Migration.Builders;

public static class ValidationBuilder
{
    public static string BuildValidationScript(
        TableMetadata table)
    {
        string columnList =
            string.Join(
                ", ",
                table.Columns.Select(
                    column => $"[{column.Name}]"));

        return $$"""
        /*
        TABLE : [{{table.Schema}}].[{{table.Name}}]
        GENERATED BY DataToolkit.Validation
        */

        SET NOCOUNT ON;

        SELECT COUNT_BIG(*) AS OnlyInTarget
        FROM
        (
            SELECT {{columnList}}
            FROM [Target].[{{table.Schema}}].[{{table.Name}}]

            EXCEPT

            SELECT {{columnList}}
            FROM [Test].[{{table.Schema}}].[{{table.Name}}]
        ) AS D;

        SELECT COUNT_BIG(*) AS OnlyInTest
        FROM
        (
            SELECT {{columnList}}
            FROM [Test].[{{table.Schema}}].[{{table.Name}}]

            EXCEPT

            SELECT {{columnList}}
            FROM [Target].[{{table.Schema}}].[{{table.Name}}]
        ) AS D;
        """;
    }
}
