<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migration\Comparers\**" />
    <Compile Remove="Migration\Writers\**" />
    <EmbeddedResource Remove="Migration\Comparers\**" />
    <EmbeddedResource Remove="Migration\Writers\**" />
    <None Remove="Migration\Comparers\**" />
    <None Remove="Migration\Writers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.59.2" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Libs\DataToolkit\DataToolkit.BulkTransfer\DataToolkit.BulkTransfer.csproj" />
    <ProjectReference Include="..\..\..\Libs\DataToolkit\DataToolkit.Library\DataToolkit.Library.csproj" />
    <ProjectReference Include="..\..\..\Libs\DataToolkit\DataToolkit.Provider.SqlLite\DataToolkit.Provider.Sqlite.csproj" />
    <ProjectReference Include="..\..\..\Libs\DataToolkit\DataToolkit.Provider.SqlServer\DataToolkit.Provider.SqlServer.csproj" />
    <ProjectReference Include="..\..\Core\Application\Application.csproj" />
    <ProjectReference Include="..\..\Core\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
